apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: social-network
spec:
  containers:
  - image: centos:8
    name: centos
    command: ["/bin/sleep", "1d"]
    volumeMounts:
    - name: media-config-pvc
      mountPath: /media-config
    - name: nginx-config-pvc
      mountPath: /nginx-config
  restartPolicy: Never
  volumes:
  - name: media-config-pvc
    persistentVolumeClaim:
      claimName: media-config-pvc
  - name: nginx-config-pvc
    persistentVolumeClaim:
      claimName: nginx-config-pvc
