---
apiVersion: v1
kind: Service
metadata:
  name: compose-post-redis
  labels:
    death-star-project: social-network
    app-name: compose-post-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    death-star-project: social-network
    app-name: compose-post-redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: compose-post-redis-config
  namespace: social-network
data:
  redis-config: |
    maxmemory 1024mb
    maxmemory-policy allkeys-lru  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: compose-post-redis
  labels:
    death-star-project: social-network
    app-name: compose-post-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: compose-post-redis
  template:
    metadata:
      annotations:
        io.cilium.proxy-visibility: "<Egress/9090/TCP/HTTP>,<Egress/6379/TCP/REDIS>,<Egress/11211/TCP/MEMCACHED>,<Egress/27107/TCP/MONGODB>,<Egress/5672/TCP/RABBITMQ>,<Ingress/9090/TCP/HTTP>,<Ingress/6379/TCP/REDIS>,<Ingress/11211/TCP/MEMCACHED>,<Ingress/27017/TCP/MONGODB>,<Ingress/5672/TCP/RABBITMQ>"

      labels: 
        death-star-project: social-network
        app-name: compose-post-redis
        INPUT: compose-post-service
      name: compose-post-redis
    spec:
      containers:
      - name: compose-post-redis
        image: redis:alpine
        command:
        - redis-server
        - "/redis-master/redis.conf"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: config
          mountPath: /redis-master
      restartPolicy: Always
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: compose-post-redis-pvc
      - name: config
        configMap:
          name: compose-post-redis-config
          items:
          - key: redis-config
            path: redis.conf
      # nodeName: 10.0.0.13
      # schedulerName: poseidon
